# Generated by Django 5.1 on 2024-09-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerceapp/BrandImages/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 6, 0, 13, 7, 206990)),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerceapp/ProductImages/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 6, 0, 13, 7, 206990)),
        ),
    ]
