# Generated by Django 5.1 on 2024-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_brands_brand_image_alter_products_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='ecommerceapp/settingImages/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ecommerceapp/settingImages/')),
                ('site_title', models.CharField(max_length=255)),
                ('Sologun', models.CharField(max_length=255)),
                ('free_shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_days', models.PositiveIntegerField()),
                ('copyright_year', models.CharField(max_length=255)),
                ('copyright_name', models.CharField(max_length=255)),
                ('distributor_by', models.CharField(max_length=255)),
                ('facebook_url', models.URLField(max_length=500)),
                ('twitter_url', models.URLField(max_length=500)),
                ('instagram_url', models.URLField(max_length=500)),
                ('linkedin_url', models.URLField(max_length=500)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=500)),
                ('phone_number', models.CharField(max_length=255)),
                ('location_url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
