# Generated by Django 5.1 on 2024-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_settings_alter_products_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_feature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_trending',
            field=models.BooleanField(default=True),
        ),
    ]
