# Generated by Django 5.1 on 2024-09-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerceapp/settingImages/'),
        ),
    ]
