# Generated by Django 5.1 on 2024-10-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='dealImage',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerceapp/deal'),
        ),
    ]
