# Generated by Django 5.1 on 2024-10-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_rename_dealimage_deal_deal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateField(),
        ),
    ]
