# Generated by Django 5.1 on 2024-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_alter_deal_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
