# Generated by Django 5.1 on 2024-10-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0018_order_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_per',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
